# -*- coding: utf-8 -*-                                                        

import os
import sys 
import pywikibot
import pywikibot_utils

def gen_lang(dict_name, result):
    for family in dict_name:
        for lang in dict_name[family]:
            result.add(lang)

def gen_all_lang():
    result = set()

    for lang in pywikibot_utils.get_all_lang('wikisource'):
        result.add(lang)

    return result

def name_from_ns(namespaces, ns):
    return namespaces[ns][0]

def gen_namespace(lang):
    site = pywikibot.Site(lang, 'wikisource')
    text = u'namespaces["wikisource"]["' + lang + '"] = {\n'
    
    namespaces = site.namespaces()
    for ns in namespaces:
        for name in namespaces[ns]:
            if name:
                text += u'    "' + name + u'" : ' + unicode(ns) + u',\n'
    text += u'}\n'

    data = pywikibot_utils.proofread_info(lang)['proofreadnamespaces']

    text += u'index["wikisource"]["' + lang + '"] = '
    text += u'"' + name_from_ns(namespaces, data[u'index'][u'id']) + u'"\n'

    text += u'page["wikisource"]["' + lang + '"] = '
    text += u'"' + name_from_ns(namespaces, data[u'page'][u'id']) + u'"\n'

    return text

def gen_all_namespace(langs):
    text  = u'# -*- coding: utf-8 -*-\n'
    text += u'# auto-generated by %s, do not edit manually.\n\n' % sys.argv[0]

    text += u"namespaces = {}\n"
    # FIXME: not really correct, works only for wikisource atm, no big deal
    text += u'namespaces["wikisource"] = {}\n\n'

    text += u'index = {}\n'
    text += u'index["wikisource"] = {}\n\n'

    text += u'page = {}\n'
    text += u'page["wikisource"] = {}\n\n'

    for lang in langs:
        text += gen_namespace(lang)
    return text

if __name__ == "__main__":
    langs = gen_all_lang()
    text = gen_all_namespace(langs)

    target = os.path.expanduser('~/wikisource/ws_namespaces.py')
    old_text = ''
    if os.path.exists(target):
        fd = open(target, 'r')
        old_text = fd.read()
        fd.close()
    if unicode(old_text, 'utf-8') != text:
        print "writing file, match and split server needs a restart"
        fd = open(target, 'w')
        fd.write(text.encode('utf-8'))
        fd.close()
