#!/bin/bash
cd /data/project/phetools/public_html/graphs
for i in Wikisource*.png; do convert -thumbnail 250 $i thumb/$i ; done
cd /data/project/phetools/phe/statistics
./stats -y > /data/project/phetools/public_html/data/stats.txt
./stats -y -d > /data/project/phetools/public_html/data/stats_diff.txt

