#!/usr/bin/env python
# -*- coding: utf-8 -*-

import re
import sys
import urllib

sys.path.append("/home/phe/wsbot")
import get_credit

def get_params(query_string):
    params = query_string.split("&")
    rdict = {}
    for param in params:
        [key, value] = param.split("=")
        rdict[key] = urllib.unquote(value)
    return rdict

def myapp(environ, start_response):
    if environ.has_key('QUERY_STRING'):
        query_string = environ['QUERY_STRING']
    else:
        query_string= 'lang=fr&book=Michaud - Biographie universelle ancienne et moderne - 1843 - Tome 1.djvu'
    #postdata = environ['wsgi.input'].read(int(environ['CONTENT_LENGTH']))
    params = get_params(query_string)
    conn = get_credit.create_conn(domain = params['lang'])
    result = get_credit.get_credit(conn, params['book'], domain = params['lang'])
    start_response('200 OK', [('Content-Type', 'text/plain; charset=UTF-8')])
    return [ str(result) ]

if __name__ == "__main__":
    from flup.server.cgi import WSGIServer
    WSGIServer(myapp).run()
